name: car_rental_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  uuid: ^4.5.2
  get_it: ^9.1.1
  flutter_platform_widgets: ^8.0.0
  supabase_flutter: ^2.10.3
  app_links: ^6.4.1
  intl_phone_number_input: ^0.7.5
  cupertino_native: ^0.1.1
  adaptive_platform_ui: ^0.1.100
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/test_cars/
    - assets/logos/
